-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 21:16:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DW
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DW` DEFAULT CHARACTER SET utf8;
USE `DW`;

-- -----------------------------------------------------
-- Table `DW`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW`.`turno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW`.`candidato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(20) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW`.`local` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `zona` VARCHAR(45) NULL,
  `secao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW`.`eleicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW`.`eleicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW`.`voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW`.`voto` (
  `turno_id` INT NOT NULL,
  `eleicao_id` INT NOT NULL,
  `candidato_id` INT NOT NULL,
  `local_id` INT NOT NULL,
  `quantidade` INT NULL,
  `porcentagem_cargo` FLOAT NULL,
  `porcentagem_valido_cargo` FLOAT NULL,
  INDEX `fk_voto_turno_idx` (`turno_id` ASC),
  INDEX `fk_voto_candidato1_idx` (`candidato_id` ASC),
  INDEX `fk_voto_local1_idx` (`local_id` ASC),
  PRIMARY KEY (`turno_id`, `eleicao_id`, `candidato_id`, `local_id`),
  INDEX `fk_voto_eleicao1_idx` (`eleicao_id` ASC),
  CONSTRAINT `fk_voto_turno`
    FOREIGN KEY (`turno_id`)
    REFERENCES `DW`.`turno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `DW`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_local1`
    FOREIGN KEY (`local_id`)
    REFERENCES `DW`.`local` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_eleicao1`
    FOREIGN KEY (`eleicao_id`)
    REFERENCES `DW`.`eleicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW`.`candidatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW`.`candidatura` (
  `candidato_id` INT NOT NULL,
  `eleicao_id` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `partido` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`candidato_id`, `eleicao_id`),
  INDEX `fk_candidato_eleicao_candidato1_idx` (`candidato_id` ASC),
  INDEX `fk_candidato_eleicao_eleicao1_idx` (`eleicao_id` ASC),
  CONSTRAINT `fk_candidato_eleicao_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `DW`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_eleicao_eleicao1`
    FOREIGN KEY (`eleicao_id`)
    REFERENCES `DW`.`eleicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW`.`candidato_scd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW`.`candidato_scd` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `data` DATETIME NULL DEFAULT NOW(),
  `candidato_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidato_scd_candidato1_idx` (`candidato_id` ASC),
  CONSTRAINT `fk_candidato_scd_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `DW`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO turno (numero) VALUES (1);
INSERT INTO turno (numero) VALUES (2);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
